export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const SET_HEADER_CLASS = 'SET_HEADER_CLASS';
export const ADD_USER = 'ADD_USER';

export const SET_SIGNUP_STEP = 'SET_SIGNUP_STEP';
export const SET_SIGNUP_EMAIL = 'SET_SIGNUP_EMAIL';
export const SET_SIGNUP_ID = 'SET_SIGNUP_ID';
export const SET_SIGNUP_FIELDS = 'SET_SIGNUP_FIELDS';

export const SET_PRICING_PLAN = 'SET_PRICING_PLAN';
export const ADD_PRICING_OPTION = 'ADD_PRICING_OPTION';
export const REMOVE_PRICING_OPTION = 'REMOVE_PRICING_OPTION';
export const ADD_PRICING_OPTION_SUB = 'ADD_PRICING_OPTION_SUB';
export const REMOVE_PRICING_OPTION_SUB = 'REMOVE_PRICING_OPTION_SUB';
